version: '3.8'

services:
  # # app:
  #   build:
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports: 
      - 27017:27017

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: unless-stopped
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/
  redis:
    image: bitnami/redis:7.0.8
    environment:
      - ALLOW_EMPTY_PASSWORD = yes